### ISSUE TITLE
Make logo render clearer in chrome

### ISSUE THREAD

**Issue by mensch72** [pik-gane/vodle#59]
probably by providing correct resolution version

**Comment by Sushmey** [comment]
Hi, I would like to try helping you. What do you mean when you say "make logo render clearer in chrome"?
<img width="618" alt="Screenshot 2022-07-31 at 12 39 41 PM" src="https://user-images.githubusercontent.com/71403193/182014470-40432271-0a0f-4656-8611-1d707be43c16.png">

**Comment by mensch72** [comment]
Hi Sushmey, thank you for your offer and sorry for being unclear. This issue is about the menu in the app, where the logo looks like this in Chrome:
![image](https://user-images.githubusercontent.com/22815964/182014648-6b7b3db0-d956-4bfc-82be-b1b82b74bd9d.png)
It seems to be antialiased in a different, less crisp way than in, say, Firefox, where it looks like this:
![image](https://user-images.githubusercontent.com/22815964/182014682-c57c0e5f-2e9b-435a-aaa0-e7c366a22dc9.png)
I guess the issue is a image size/resolution one. The place in code where the logo is referenced is in src/app/app.component.html, and the image is in assets/topleft_icon.png. Maybe something with the <img> tag or the image file itself needs to be done, like rescaling or something.

**Comment by mensch72** [comment]
Hm, I added
```
html {
    image-rendering: webkit-optimize-contrast;
}
```
but it doesn't seem to make a difference.

**Comment by Wojtekb30** [comment]
Hello.
First, Chrome and Firefox have different rendering engines. But I don't think that's really the issue here.
What I noticed is that the base image is too small. The browser has to upscale it, and as we know, making a small image bigger makes it look worse.
First, I would try putting a bigger full-res logo file, bigger than what finally renders (downscaling always looks better than upscaling, and it won't visibly affect performance).
Secondary, I would recommend trying using other image file types, like jpg, gif etc. 
I would most recommend converting the logo to .svg and using the svg version, since vector graphics don't lose quality when changing size. I've seen websites which similarly render their logo in top left, and they use svg (vector) logo.
If you'd like, I can try to test and implement what's needed myself.
Thank you for considering my tips and I hope that I helped.

**Comment by mensch72** [comment]
Hi @Wojtekb30 , thank you for your considerations!

I am a little confused by your statement that the base image be too small. The png file src/assets/topleft_icon.png which is used has a width of 784 pixels, which is surely larger than the size it will be rendered in in the top left corner on any device I can imagine, or isn't it?

Anyway, I tested replacing it with an svg version, and that works well. I should have thought of this trivial solution myself, I actually don't know why I didn't. 

So the issue is solved, thank you for helping out!
